### ISSUE TITLE
Row tooltip not evaluating in Web Player

### ISSUE THREAD

**Issue by f1li** [hski-github/spotfire-sankey-diagram#19]
I am having this strange issue only in webplayer. See picture for details (NaN showing up)

![image](https://user-images.githubusercontent.com/74111096/122021931-6d8b5a80-cdc6-11eb-82de-2cb58bc4c6be.png)

**Comment by hski-github** [comment]
Thank you for getting in contact. It is really great to see others making use of my mod. And it is good to get information about possible issues with the mod. Thanks for reporting! :-) Could you provide a sample data set and instructions to reproduce the issue?

**Comment by hski-github** [comment]
I checked with TIBCO mod team and they are very surprised to see such an issue because there is no difference in rendering on client vs. web and therefor getting more details about this critical issue would be very helpful. Hopefully it was just a glitch in local dev environment and will disappear after refresh? Thank you in advance for any details about this issue.

**Comment by f1li** [comment]
Holger we have tried again this yesterday on my boss pc...it was still there. Will check again later with latest code. Very very strange.

**Comment by hski-github** [comment]
What web browser are you using?

**Comment by f1li** [comment]
I am using google chrome. Howevere with latest code this seems fixed. Thanks so much again Holger.

**Comment by hski-github** [comment]
Okay, good to know. If issues pops up again, please provide feedback, because this would be critical issue.

**Comment by f1li** [comment]
For sure, I will do.
